alias: Turn off Living Room Lights
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_occupied
    to: 'off'
action:
  - service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 0