alias: Dispense dinner for cat (away)
trigger:
  - platform: time
    at: '19:00:00'
condition:
  - condition: state
    entity_id: device_tracker.grayson
    state: 'not_home'
action:
  - service: script.turn_on
    entity_id: script.feed_cat